apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
 name: infadapter-podmonitor
 namespace: monitoring
 labels:
   podmonitor: infadapter
spec:
 namespaceSelector:
   any: true
 podMetricsEndpoints:
 - interval: 1s
   path: /metrics
 selector:
   matchLabels:
     project: infadapter
