apiVersion: v1
kind: ConfigMap
metadata:
  name: tfserving-resnet-cm
data:
  models.config: |-
    model_config_list {
      config {
        name: 'resnet'
        base_path: '/models/resnet/'
        model_platform: 'tensorflow'
        model_version_policy {
          specific {
            versions: 50
          }
        }
      }
    }
