apiVersion: v1
kind: ConfigMap
metadata:
  name: tfserving-resnet-cm
data:
  models.config: |-
    model_config_list {
      config {
        name: 'resnet'
        base_path: '/models/resnet/'
        model_platform: 'tensorflow'
        model_version_policy {
          specific {
            versions: 50
          }
        }
      }
    }
  batch.config: |-
    max_batch_size { value: 16 }
    batch_timeout_micros { value: 0 }
    max_enqueued_batches { value: 1000000 }
    num_batch_threads { value: 2 }
